---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-fast-disks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: fast-disks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        backup.velero.io/backup-volumes: my-storage
    spec:
      containers:
      - image: nginx:1.17.6
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: pvc-fast-disks
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
