apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-rook-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
